/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "unistd.h"
#include "Motor_L298N.h"



int main(void)
{
	 MotorSystem_Config_t motors = {
	        // Left Forward Motor (L298N #1)
			 .left_forward = {
	            .GPIOx = GPIOA,
	            .IN1_Pin = GPIO_PIN_0,
	            .IN2_Pin = GPIO_PIN_1,
	            .TIMx = TIM2_SELECT,
	            .PWM_Frequency = 1000,
	            .PWM_Channel = 1
	        },
	        // Right Forward Motor (L298N #1)
	        .right_forward = {
	            .GPIOx = GPIOA,
	            .IN1_Pin = GPIO_PIN_2,
	            .IN2_Pin = GPIO_PIN_3,
	            .TIMx = TIM2_SELECT,
	            .PWM_Frequency = 1000,
	            .PWM_Channel = 2
	        },
	        // Left Backward Motor (L298N #2)
	        .left_backward = {
	            .GPIOx = GPIOB,
	            .IN1_Pin = GPIO_PIN_0,
	            .IN2_Pin = GPIO_PIN_1,
	            .TIMx = TIM3_SELECT,
	            .PWM_Frequency = 1000,
	            .PWM_Channel = 1
	        },
	        // Right Backward Motor (L298N #2)
	        .right_backward = {
	            .GPIOx = GPIOB,
	            .IN1_Pin = GPIO_PIN_6,
	            .IN2_Pin = GPIO_PIN_7,
	            .TIMx = TIM4_SELECT,
	            .PWM_Frequency = 1000,
	            .PWM_Channel = 1
	        }
	    };

	 	    MotorSystem_Init(&motors);
	 	    Move_Forward(&motors, 50);
	    	Move_Left(&motors, 70);  // Left motors at 70%, right stopped
	        Delay_ms(3000);

	        Move_Right(&motors, 70); // Right motors at 70%, left stopped
	        Delay_ms(3000);

	        Stop_All(&motors);
	        Delay_ms(1000);

	    while(1) {

	    }
}

